l_cost = [ { "prod_id" : 1,"prod_cost" : 7}
          ,{ "prod_id" : 2,"prod_cost" : 4}
          ,{ "prod_id" : 3,"prod_cost" : 2}
          ,{ "prod_id" : 4,"prod_cost" : 6}
          ,{ "prod_id" : 5,"prod_cost" : 3}
          ,{ "prod_id" : 6,"prod_cost" : 5}
          ,{ "prod_id" : 7,"prod_cost" : 10}
          ,{ "prod_id" : 8,"prod_cost" : 9}
          ,{ "prod_id" : 9,"prod_cost" : 2}
          ,{ "prod_id" : 10,"prod_cost" : 3}
          ,{ "prod_id" : 11,"prod_cost" : 23}
          ,{ "prod_id" : 12,"prod_cost" : 1}
          ,{ "prod_id" : 13,"prod_cost" : 7}
          ,{ "prod_id" : 14,"prod_cost" : 4}
          ,{ "prod_id" : 15,"prod_cost" : 8}
          ,{ "prod_id" : 16,"prod_cost" : 3}
          ,{ "prod_id" : 17,"prod_cost" : 2}
          ,{ "prod_id" : 18,"prod_cost" : 14}
          ,{ "prod_id" : 19,"prod_cost" : 5}
          ,{ "prod_id" : 20,"prod_cost" : 1}
          ,{ "prod_id" : 21,"prod_cost" : 3}
          ,{ "prod_id" : 22,"prod_cost" : 11}
          ,{ "prod_id" : 23,"prod_cost" : 9}
          ,{ "prod_id" : 24,"prod_cost" : 18}
          ,{ "prod_id" : 25,"prod_cost" : 3}]